### ISSUE TITLE
Use github milestones

### ISSUE THREAD

**Issue by Jonas-Karl** [DHBW-Mailflow/mailserver#65]
**Description**
As a product owner ] I want to have an organised project so that the sprints can be planned easier

**Ready Criteria**
- [ ] everyone understood the scope of this ticket
- [ ] atleast one person is assigned

**Acceptance Criteria**
- [ ] milestones are set up with a good chosen deadline

**Scope**
- [ ] configuration

**Additional context**
